*** Variables ***
${veeam_logo}  	xpath://img[@class='img-logo']
${all_departments_dropdown}  xpath://button[contains(text(),'All departments')]
${select_research&development_department}  xpath://a[contains(text(),'Research & Development')]
${all_languages}  xpath://button[contains(text(),'All languages')]
${english_language_checkbox}  xpath://input[@id='lang-option-0']
${jobs_list}  xpath://div[@class='h-100 d-flex flex-column']
${job_card}  xpath://a[@class='card card-sm card-no-hover']